### ISSUE TITLE
Poprawka dla 4 punktu 

### ISSUE THREAD

**Issue by derekqq** [Duszek/pgg#1]
Możesz w 4 punkcie dopisać że zamiast odświeżać główna to dobrze odświeżać sprawdź węgiel wtedy redukujemy ryzyko bana przez za częste odświeżanie.

**Comment by Duszek** [comment]
Ok, ale czy odświeżając sprawdzwegiel.pl nie muszę potem tak czy siak odświeżyć strony głównej sklepu czy koszyka (a co za tym idzie dobić się do niego przez wszystkie zabezpieczenia, czyli N odświeżeń)? Bo poza zmniejszeniem ilości strzałów do PGG odświeżanie sprawdzwegiel.pl sprawia, że jestem w plecy czasowo. W tym samym czasie mam szansę zobaczyć dostępność już na PGG. Ja przy stosowaniu tej instrukcji zostałem tylko raz uznany za bota i to na nie dłużej niż 1-2 minuty. Potem puściło.
Dodam do instrukcji, bo jest to dodatkowa metoda i ma to sens o którym wspomniałeś, ale nie widzę 100% uzysku - wyprowadź mnie z błędu, jeśli coś źle rozumiem. :)

**Comment by Duszek** [comment]
Strona nie pokazuje jeszcze Karlika 1t, a ja już mam w koszyku ;)

**Comment by Duszek** [comment]
Strona dalej nie pokazuje Karlika 1t, a ja już mam kupione kolejne 2 tony ;)

**Comment by derekqq** [comment]
No niestety jest problem z cache przy dużej ilości osób za bardzo nie mam pomysłu jak to na tą chwile rozwiązać. Jako tako aktualizacje były na bieżąco najlepiej odpalac w trybie incognito

**Comment by derekqq** [comment]
wdrożyłem małą poprawkę więc od wtorku nie powinno być problemu z cache.

**Comment by derekqq** [comment]
> Ok, ale czy odświeżając sprawdzwegiel.pl nie muszę potem tak czy siak odświeżyć strony głównej sklepu czy koszyka (a co za tym idzie dobić się do niego przez wszystkie zabezpieczenia, czyli N odświeżeń)? Bo poza zmniejszeniem ilości strzałów do PGG odświeżanie sprawdzwegiel.pl sprawia, że jestem w plecy czasowo. W tym samym czasie mam szansę zobaczyć dostępność już na PGG. Ja przy stosowaniu tej instrukcji zostałem tylko raz uznany za bota i to na nie dłużej niż 1-2 minuty. Potem puściło. Dodam do instrukcji, bo jest to dodatkowa metoda i ma to sens o którym wspomniałeś, ale nie widzę 100% uzysku - wyprowadź mnie z błędu, jeśli coś źle rozumiem. :)

Jeśli chodzi o zysk to możesz mieć główna zaladowana wcześniej z odblokowanym przyciskiem i z takiego stanu dodawać z ctrl wtedy robi się to dużo wydajniej.

**Comment by Duszek** [comment]
Dodałem wzmiankę o sprawdzwegiel.pl i info o zedytowaniu sobie źródła strony
